### ISSUE TITLE
Documentation build failed

### ISSUE THREAD

**Issue by fantix** [decentfox/aioh2#1]
```
Running Sphinx v1.3.4
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aioh2/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aioh2/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aioh2/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 279, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
ConfigError: There is a syntax error in your configuration file: invalid syntax (helper.py, line 34)

Configuration error:
There is a syntax error in your configuration file: invalid syntax (helper.py, line 34)
```

**Comment by wwwjfy** [comment]
readthedocs => Admin => Advanced Settings => Python interpreter => CPython 3.x

**Comment by fantix** [comment]
原来如此
